CREATE TABLE IF NOT EXISTS films(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    year_of_release int NOT NULL ,
    age_restrictions VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    poster_for_a_movie varchar(255)
    );



CREATE TABLE IF NOT EXISTS halls(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial INT NOT NULL UNIQUE,
    seats INT NOT NULL
);


CREATE TABLE IF NOT EXISTS sessions(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   hall_id INT NOT NULL ,
   film_id INT NOT NULL,
   start_at TIMESTAMP NOT NULL,
   cost int NOT NULL,
   FOREIGN KEY (hall_id) REFERENCES halls(id),
   FOREIGN KEY (film_id) REFERENCES films(id)
);

drop table messages;

CREATE TABLE IF NOT EXISTS messages(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   film_id INT NOT NULL,
   username VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_avatar VARCHAR(255),
    FOREIGN KEY (film_id) REFERENCES films(id)
    );

